language: ruby
script: "bundle exec rake test"
cache: bundler
sudo: false
rvm:
  - '2.3.0'
  - '2.2'
  - '2.1'

gemfile:
  - gemfiles/am_3_2.gemfile
  - gemfiles/am_4_0.gemfile
  - gemfiles/am_4_1.gemfile
  - gemfiles/am_4_2.gemfile

notifications:
  email: false
